name: mimikami

packages:
  - packages/**

scripts:
  analyze:
    exec: flutter analyze .
  build_runner_build_d:
    exec: flutter pub run build_runner build -d 
  build_runner_watch_d:
    exec: flutter pub run build_runner watch -d 
